---
title: "Final Project"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 60), tidy = TRUE)
library(lmtest)
library(forecast)
library(vars)
library(tseries)
```



```{r}
setwd("/Users/minchenwang/classes/604/project")
df <- read.csv("new_data.csv", header=T)
df1 <- df[1:318,]
df2 <- df[319:354,]
full_bank <- ts(df1$Bankruptcy_Rate, start=c(1988,7),frequency = 12)
full_unemploy <- ts(df1$Unemployment_Rate, start=c(1988,7),frequency = 12)
full_unemploy_test <- ts(df2$Unemployment_Rate, start=2015,frequency = 12)
lambda <- BoxCox.lambda(full_bank)
model <- Arima(full_bank, order =c(5,1,6), seasonal =list(order =c(1,0,2), period = 12), lambda =lambda, method = 'CSS',xreg = data.frame(full_unemploy))
summary(model)
f <- forecast(model, h=36, level = 0.95, xreg = data.frame(full_unemploy_test))
```


```{r}
# Get the data
setwd("/Users/minchenwang/classes/604/project")
df <- read.csv("new_data.csv", header=T)
unemploy <- ts(df$Unemployment_Rate, start=c(1988,7),frequency = 12)
pop <- ts(df$Population, start=c(1988,7),frequency = 12)
house <- ts(df$House_Price_Index, start=c(1988,7),frequency = 12)
head(df)
```

```{r}
df1 <- df[1:318,]
df2 <- df[319:354,]
# get the full train data before spliting
full_bank <- ts(df1$Bankruptcy_Rate, start=c(1988,7),frequency = 12)
full_unemploy <- ts(df1$Unemployment_Rate, start=c(1988,7),frequency = 12)
full_pop <- ts(df1$Population, start=c(1988,7),frequency = 12)
full_house <- ts(df1$House_Price_Index, start=c(1988,7),frequency = 12)
full_unemploy_test <- ts(df2$Unemployment_Rate, start=2015,frequency = 12)
full_pop_test <- ts(df2$Population,start=2015,frequency = 12)
full_house_test <- ts(df2$House_Price_Index, start=2015,frequency = 12)
```


```{r}
# get our own train(282 months) and test(36 months) data
n_months <- 36
end_year <- 2014
df1_train <- df1[1:(nrow(df1)- n_months),]
df1_test <- df1[(nrow(df1)- n_months + 1):nrow(df1),]
train <- ts(df1_train$Bankruptcy_Rate, start=c(1988,7),frequency = 12)
test <- ts(df1_test$Bankruptcy_Rate,frequency = 12, start = c((end_year-n_months/12+1)))
Unemployment_Rate <- ts(df1_train$Unemployment_Rate, start=c(1988,7),frequency = 12)
Population <- ts(df1_train$Population,start=c(1988,7), frequency = 12)
House_Price_Index <- ts(df1_train$House_Price_Index, start=c(1988,7),frequency = 12)
Unemployment_Rate_test <- ts(df1_test$Unemployment_Rate, frequency = 12, start = c((end_year-n_months/12+1)))
Population_test <- ts(df1_test$Population, frequency = 12,start = c((end_year-n_months/12+1)))
House_Price_Index_test <- ts(df1_test$House_Price_Index, frequency = 12,start = c((end_year-n_months/12+1)))
plot(train, xlim = c(1988,2014))
lines(test, col = 'blue')
```

```{r}
par(mfrow=c(3,1))
plot(full_unemploy)
plot(full_house)
plot(full_pop)
```

# SARIMAX Model

Use Box-Jenkins Methodology to do the data transformation
```{r}
lambda <- BoxCox.lambda(train)
train_trans <- (train^lambda-1)/lambda
plot(ntrain_trans), ylab='transformed bankruptcy rate')
```

Check how many time differences is necessary
```{r}
print(ndiffs(train_trans))
print(nsdiffs(train_trans))
```

```{r}
# differencing once
dtrain_trans <- diff(train_trans)
adf.test(dtrain_trans)
```
stationary pass

```{r}
plot(dtrain_trans)
```

```{r}
par(mfrow=c(2,1))
acf(dtrain_trans, lag.max = 72)
pacf(dtrain_trans, lag.max = 72)
```


```{r}
par(mfrow=c(3,1))
ccf(train_trans, full_house)
ccf(train_trans, full_pop)
ccf(train_trans, full_unemploy)
```
seems all have highest correlation when lag=0

find the best arima
```{r,eval=F}
p_vec <- c()
q_vec <- c()
P_vec <- c()
Q_vec <- c()
aic_vec <- c()
sigma_vec <- c()
loglik_vec <- c()
rmse_vec <- c()
for (p in 2:6){
  for (q in 2:6){
    for (P in 1:6){
      for (Q in 1:6){
        # print(paste(p,q,P,Q))
        tryCatch({
        model <- Arima(train,lambda = lambda, method = "CSS",order = c(p,1,q),seasonal = list(order = c(P,0,Q), period = 12))
        fore <- forecast(model, h=n_months)
        p_vec <- append(p_vec, p)
        q_vec <- append(q_vec, q)
        P_vec <- append(P_vec, P)
        Q_vec <- append(Q_vec, Q)
        rmse <- accuracy(fore,test)[2,2]
        rmse_vec <- append(rmse_vec, rmse)
        aic_vec <- append(aic_vec,model$aic)
        sigma_vec <- append(sigma_vec,model$sigma2)
        loglik_vec <- append(loglik_vec,model$loglik)})
      }
    }
  }
}
d <- data.frame(p_vec,q_vec,P_vec,Q_vec,sigma_vec, aic_vec,loglik_vec, rmse_vec)
```


```{r}
# build ARIMA model
m1 <- Arima(train, order =c(5,1,5), seasonal =list(order =c(1,0,2), period = 12), lambda =lambda, method = 'CSS',xreg = data.frame(Unemployment_Rate))
summary(m1)
```

```{r}
f1 <- forecast(m1, h=36, level = 0.95, xreg = data.frame(Unemployment_Rate_test))
```

```{r}
m2 <- Arima(train, order =c(5,1,6), seasonal =list(order =c(1,0,2), period = 12), lambda =lambda, method = 'CSS',xreg = data.frame(Unemployment_Rate))
summary(m2)
```

```{r}
f2 <- forecast(m2, h=n_months, level = 0.95, xreg = data.frame(Unemployment_Rate_test))
accuracy(f2,test)
```

```{r}
m3 <- Arima(train, order =c(5,1,6), seasonal =list(order =c(1,0,4), period = 12), lambda =lambda, method = 'CSS',xreg = data.frame(Unemployment_Rate))
summary(m3)
```

```{r}
f3 <- forecast(m3, h=n_months, level = 0.95, xreg = data.frame(Unemployment_Rate_test))
accuracy(f3,test)
```


```{r}
m4 <- Arima(train, order =c(5,1,4), seasonal =list(order =c(1,0,2), period = 12), lambda =lambda, method = 'CSS',xreg = data.frame(Unemployment_Rate,House_Price_Index))
summary(m4)
```

```{r}
f4 <- forecast(m4, h=n_months, level = 0.95, xreg = data.frame(Unemployment_Rate_test,House_Price_Index_test))
accuracy(f4,test)
```

```{r}
m5 <- Arima(train, order =c(5,1,4), seasonal =list(order =c(1,0,4), period = 12), lambda =lambda, method = 'CSS',xreg = data.frame(Unemployment_Rate,House_Price_Index))
summary(m5)
```

```{r}
f5 <- forecast(m5, h=n_months, level = 0.95, xreg = data.frame(Unemployment_Rate_test,House_Price_Index_test))
accuracy(f5,test)
```

```{r}
# test on whole train data 
lambda <- BoxCox.lambda(full_bank)
model <- Arima(full_bank, order =c(5,1,6), seasonal =list(order =c(1,0,2), period = 12), lambda =lambda, method = 'CSS',xreg = data.frame(full_unemploy))
summary(model)
```
```{r}
f <- forecast(model, h=36, level = 0.95, xreg = data.frame(full_unemploy_test))
```



```{r}
# plot forecast
plot(full_bank, type = "l", xlim=c(1988,2017),ylim=c(0,7), ylab='bankruptcy_rate')
t1 <- time(full_bank)
fit <- ts(f$fitted,start=c(1987,7),frequency = 12)
points(t1, fit, type = "l", col = "red")
point <- ts(f$mean,start=2015,frequency = 12)
lower <- ts(f$lower,start=2015,frequency = 12)
upper <- ts(f$upper,start=2015,frequency = 12)
abline(v=2015,col='blue',lty=2)
t2 <- time(full_unemploy_test)
polygon(c(t2, rev(t2)), c(upper, rev(lower)), col = "grey90", border = NA)
points(point~t2, type='l', col='red')
legend("topleft", legend = c("Observed", "Predicted", "95% Interval"),
       lty = 1, lwd = c(1,1,10), col = c("black", "red", "grey90"), cex = 1)
```



```{r}
# try SARIMAX but not works better
model <- Arima(train, order =c(5,1,5), seasonal =list(order =c(1,0,2), period = 12), lambda =lambda, method = 'CSS',xreg = data.frame(Unemployment_Rate))
summary(m2)
```

```{r}
f2 <- forecast(m2, h=n_months, xreg = data.frame(Unemployment_Rate_test),level = 0.95)
accuracy(f2,test)
```



```{r}
# plot forecast
fit <- ((train_trans - m2$residuals)*lambda + 1)^(1/lambda)
plot(train, type = "l", main = "Bankruptcy Rate", xlim=c(1988,2014),ylim=c(0,7))
t1 <- time(train)
points(t1, fit, type = "l", col = "red")
point <- f2$mean
lower <- f2$lower
upper <- f2$upper
abline(v=2012,col='blue',lty=2)
t2 <- time(test)
polygon(c(t2, rev(t2)), c(upper, rev(lower)), col = "grey90", border = NA)
points(point~t2, type='l', col='red')
points(test[1:36]~t2, type='l', col='black')
legend("topleft", legend = c("Observed", "Predicted", "Interval"),
       lty = 1, lwd = c(1,1,10), col = c("black", "red", "grey90"), cex = 1)
```


```{r}
# test on whole train data 
model <- Arima(full_bank, order =c(5,1,6), seasonal =list(order =c(1,0,2), period = 12), lambda =lambda, method = 'CSS',xreg = data.frame(full_pop))
summary(model)
```

# VAR
```{r}
VARselect(y = data.frame(train, Unemployment_Rate))
```

by trying different p, got lowest rmse when p=5
```{r, error=FALSE}
m.var <- VAR(y = data.frame(train, Unemployment_Rate), p = 10)
```

```{r}
# Let's now do some forecasting with this model
forecast_var <-predict(m.var, n.ahead = 36, ci = 0.95)
```

```{r}
rmse_var <-sqrt(mean((forecast_var$fcst$train[,1]-test)^2))
rmse_var
```

```{r}
m.var2 <- VAR(y = data.frame(full_bank, full_unemploy, full_house, full_pop), p = 5)
```

```{r}
forecast_var2 <-predict(m.var2, n.ahead = 36, ci = 0.95)
plot(forecast_var2)
```

